apiVersion: 1

datasources:
  - name: prometheus-datasource
    uid: adwznwwq8yupse # THIS IS IMPORTANT ON THE DASHBOARD MUST BE THE SAME
    orgId: 1
    type: prometheus
    access: proxy
    url: http://prometheus:${PROMETHEUS_PORT}
    isDefault: true
  - name: loki-datasource
    uid: cdxkxyq1xjmyoc # THIS IS IMPORTANT ON THE DASHBOARD MUST BE THE SAME               
    orgId: 1
    type: loki
    access: proxy
    url: http://loki:${LOKI_PORT}
    isDefault: false